### ISSUE TITLE
Build docker image for Mac (arm64)

### ISSUE THREAD

**Issue by jamest-pin** [nabla-c0d3/sslyze#648]
**Is your feature request related to a problem? Please describe.**
I want to run the docker image locally at work first before deploying in CI.
Currently I get this:
```
~$ docker pull nablac0d3/sslyze:6.0.0
6.0.0: Pulling from nablac0d3/sslyze
no matching manifest for linux/arm64/v8 in the manifest list entries
```

**Describe the solution you'd like**
I'd like to be able to pull the docker image from docker hub and run it on my Mac M series.
This could be accomplished by adding one keyword `, linux/arm64` to your github actions workflow.
```yaml
     - name: Build and Push
        uses: docker/build-push-action@v2 # <<<<<<<< fyi, v5 is the latest.
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64 # <<<<<<<<< update here
```

**Describe alternatives you've considered**
I attempte to git clone and `docker build .` myself, but got some python build script error which is above my head to resolve.

**Additional context**
No additional context. Thanks in advance.
